# Generated by Django 4.2.5 on 2023-09-14 16:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CharCode', models.CharField(help_text='Сокращенное обозначение валюты', max_length=3, verbose_name='Символьный код')),
                ('value', models.FloatField(help_text='Значение в рублях', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Значение')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Время обновления')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
            },
        ),
    ]
