# Generated by Django 4.2.5 on 2023-09-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='currency',
            old_name='CharCode',
            new_name='char_code',
        ),
    ]
